# Objective :- 

* A cancerous tumor is malignant, meaning it can grow and spread to other parts of the body. A benign tumor means the tumor can grow but will not spread.

* To Predict where the patient have Cancer Malignant or not 

# Step 1 :Library & Data Import

In [5]:
import warnings
warnings.filterwarnings("ignore")

import os
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [7]:
data = pd.read_csv(r"C:\Users\lenovo\OneDrive\Desktop\HRUTUJA\Imarticus\Advanced ML\KNN\Prostate_Cancer.csv")
data.head()

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

#  Step 2 : Data Pre-Processing

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 100 non-null    int64  
 1   diagnosis_result   100 non-null    object 
 2   radius             100 non-null    int64  
 3   texture            100 non-null    int64  
 4   perimeter          100 non-null    int64  
 5   area               100 non-null    int64  
 6   smoothness         100 non-null    float64
 7   compactness        100 non-null    float64
 8   symmetry           100 non-null    float64
 9   fractal_dimension  100 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


### Removing irrelevant  

In [13]:
data.drop('id',axis=1,inplace=True)

# Step 3 : Data Partition

In [16]:
from sklearn.model_selection import train_test_split

train_x = data.drop(['diagnosis_result'],axis=1)
train_y = data['diagnosis_result']

# Train test split

X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.3,random_state=20)

In [18]:
X_train.head()

radius  texture  perimeter  area  smoothness  compactness  symmetry  \
39      10       14         88   559       0.102        0.126     0.172   
64      16       19         83   499       0.112        0.126     0.191   
72      21       12        114   929       0.107        0.183     0.193   
60      15       18         65   312       0.113        0.081     0.274   
46      22       12         52   202       0.086        0.059     0.177   

    fractal_dimension  
39              0.064  
64              0.066  
72              0.065  
60              0.070  
46              0.065

#  Step 4 : Scaling Data

In [21]:
from sklearn.preprocessing import StandardScaler ,MinMaxScaler
scaler = MinMaxScaler()   # converting data into Z-scale = X-mean / Standard Deviation
#scaler.fit(X_train)         # Mean = 0 & standard Deviation =1

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
X_train[0:5]

array([[0.0625    , 0.1875    , 0.3       , 0.21300716, 0.45070423,
        0.28664495, 0.21893491, 0.25      ],
       [0.4375    , 0.5       , 0.25833333, 0.17720764, 0.5915493 ,
        0.28664495, 0.33136095, 0.29545455],
       [0.75      , 0.0625    , 0.51666667, 0.43377088, 0.52112676,
        0.4723127 , 0.34319527, 0.27272727],
       [0.375     , 0.4375    , 0.10833333, 0.06563246, 0.6056338 ,
        0.14006515, 0.82248521, 0.38636364],
       [0.8125    , 0.0625    , 0.        , 0.        , 0.22535211,
        0.06840391, 0.24852071, 0.27272727]])

# Step 5 : Model Building 

In [26]:
model = KNeighborsClassifier(n_neighbors=6)  # k = random = 8

model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

# Step 6 : Predictions on Train Dataset

In [29]:
X_train = pd.DataFrame(X_train,columns=['radius', 'texture', 'perimeter', 'area','smoothness', 'compactness', 'symmetry', 'fractal_dimension'])
X_train.head()

radius  texture  perimeter      area  smoothness  compactness  symmetry  \
0  0.0625   0.1875   0.300000  0.213007    0.450704     0.286645  0.218935   
1  0.4375   0.5000   0.258333  0.177208    0.591549     0.286645  0.331361   
2  0.7500   0.0625   0.516667  0.433771    0.521127     0.472313  0.343195   
3  0.3750   0.4375   0.108333  0.065632    0.605634     0.140065  0.822485   
4  0.8125   0.0625   0.000000  0.000000    0.225352     0.068404  0.248521   

   fractal_dimension  
0           0.250000  
1           0.295455  
2           0.272727  
3           0.386364  
4           0.272727

In [31]:
y_train.reset_index(drop=True, inplace=True)

In [33]:
train = pd.concat([X_train,y_train],axis=1)
train.head()

radius  texture  perimeter      area  smoothness  compactness  symmetry  \
0  0.0625   0.1875   0.300000  0.213007    0.450704     0.286645  0.218935   
1  0.4375   0.5000   0.258333  0.177208    0.591549     0.286645  0.331361   
2  0.7500   0.0625   0.516667  0.433771    0.521127     0.472313  0.343195   
3  0.3750   0.4375   0.108333  0.065632    0.605634     0.140065  0.822485   
4  0.8125   0.0625   0.000000  0.000000    0.225352     0.068404  0.248521   

   fractal_dimension diagnosis_result  
0           0.250000                M  
1           0.295455                M  
2           0.272727                M  
3           0.386364                B  
4           0.272727                B

In [35]:
train['Predicted'] = model.predict(X_train)
train.head()

radius  texture  perimeter      area  smoothness  compactness  symmetry  \
0  0.0625   0.1875   0.300000  0.213007    0.450704     0.286645  0.218935   
1  0.4375   0.5000   0.258333  0.177208    0.591549     0.286645  0.331361   
2  0.7500   0.0625   0.516667  0.433771    0.521127     0.472313  0.343195   
3  0.3750   0.4375   0.108333  0.065632    0.605634     0.140065  0.822485   
4  0.8125   0.0625   0.000000  0.000000    0.225352     0.068404  0.248521   

   fractal_dimension diagnosis_result Predicted  
0           0.250000                M         M  
1           0.295455                M         M  
2           0.272727                M         M  
3           0.386364                B         B  
4           0.272727                B         B

# Step 7 : Model Performance Metrics

In [38]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(train['diagnosis_result'],train['Predicted'])
print(confusion_matrix)

[[16  5]
 [ 1 48]]


In [40]:
Accuracy_Train=((16+48)/(70)*100)
print(Accuracy_Train)

91.42857142857143


In [42]:
from sklearn.metrics import classification_report
print(classification_report(train['diagnosis_result'], train['Predicted']))

              precision    recall  f1-score   support

           B       0.94      0.76      0.84        21
           M       0.91      0.98      0.94        49

    accuracy                           0.91        70
   macro avg       0.92      0.87      0.89        70
weighted avg       0.92      0.91      0.91        70



# Step 8 : Predictions on Test Dataset

In [45]:
X_test = pd.DataFrame(X_test,columns=['radius', 'texture', 'perimeter', 'area','smoothness', 'compactness', 'symmetry', 'fractal_dimension'])
X_test.head()

radius  texture  perimeter      area  smoothness  compactness  symmetry  \
0  0.7500   0.4375   0.600000  0.553699    0.281690     0.211726  0.136095   
1  0.5625   0.1250   0.225000  0.160501    0.309859     0.097720  0.218935   
2  0.7500   1.0000   0.650000  0.597255    0.774648     0.397394  0.426036   
3  0.0625   0.2500   0.275000  0.196897    0.380282     0.218241  0.236686   
4  0.0625   0.5000   0.616667  0.566826    0.492958     0.289902  0.337278   

   fractal_dimension  
0           0.045455  
1           0.136364  
2           0.159091  
3           0.204545  
4           0.159091

In [47]:
y_test.reset_index(drop=True, inplace=True)

In [49]:
test = pd.concat([X_test,y_test],axis=1)
test.head()

radius  texture  perimeter      area  smoothness  compactness  symmetry  \
0  0.7500   0.4375   0.600000  0.553699    0.281690     0.211726  0.136095   
1  0.5625   0.1250   0.225000  0.160501    0.309859     0.097720  0.218935   
2  0.7500   1.0000   0.650000  0.597255    0.774648     0.397394  0.426036   
3  0.0625   0.2500   0.275000  0.196897    0.380282     0.218241  0.236686   
4  0.0625   0.5000   0.616667  0.566826    0.492958     0.289902  0.337278   

   fractal_dimension diagnosis_result  
0           0.045455                M  
1           0.136364                B  
2           0.159091                M  
3           0.204545                M  
4           0.159091                M

In [51]:
test['Predicted'] = model.predict(X_test)
test.head()

radius  texture  perimeter      area  smoothness  compactness  symmetry  \
0  0.7500   0.4375   0.600000  0.553699    0.281690     0.211726  0.136095   
1  0.5625   0.1250   0.225000  0.160501    0.309859     0.097720  0.218935   
2  0.7500   1.0000   0.650000  0.597255    0.774648     0.397394  0.426036   
3  0.0625   0.2500   0.275000  0.196897    0.380282     0.218241  0.236686   
4  0.0625   0.5000   0.616667  0.566826    0.492958     0.289902  0.337278   

   fractal_dimension diagnosis_result Predicted  
0           0.045455                M         M  
1           0.136364                B         B  
2           0.159091                M         M  
3           0.204545                M         M  
4           0.159091                M         M

# Step 9 : Model Performance Metrics on Test data 

In [54]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test['diagnosis_result'],test['Predicted'])
print(confusion_matrix)

[[13  4]
 [ 1 12]]


In [56]:
Accuracy_test=((13+12)/(30)*100)
Accuracy_test

83.33333333333334

In [58]:
from sklearn.metrics import classification_report
print(classification_report(test['diagnosis_result'], test['Predicted']))

              precision    recall  f1-score   support

           B       0.93      0.76      0.84        17
           M       0.75      0.92      0.83        13

    accuracy                           0.83        30
   macro avg       0.84      0.84      0.83        30
weighted avg       0.85      0.83      0.83        30



# Cross Validation Method  - 

1. K-fold inside Grid Search 

In [61]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors': np.arange(2, 8)}


knn2 = KNeighborsClassifier()
knn_gscv = GridSearchCV(knn2,
                        param_grid, # 2,3,4,5,6,7
                        cv=10, # 10-fold
                        verbose=1)
knn_gscv.fit(X_train, y_train)

Fitting 10 folds for each of 6 candidates, totalling 60 fits


GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([2, 3, 4, 5, 6, 7])}, verbose=1)

In [63]:
#check top performing n_neighbors value
knn_gscv.best_params_

{'n_neighbors': 6}

# Finish